container:
  image: python:3.11

task:
  name: test_python_package

  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python -m pip install .

  install_script:
    - python -m pip install .

  test_script:
    - python -m pytest tests/