name: Build Macos package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_macos:      
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"] 
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with: 
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-benchmark
    - name: Install package
      run: |
        python -m pip install --verbose .
    - name: Test with pytest
      run: |
        python -m pytest tests/ --cov=skpackage --benchmark-skip
        coverage report -m
    - name: Uninstall the package
      run: |
        python -m pip uninstall --verbose -y skpackage
    - name: Build a wheel
      run: |
        python -m pip wheel . --no-deps --wheel-dir $GITHUB_WORKSPACE/dist 
    - name: Install the wheel
      run: | 
        python -m pip install $GITHUB_WORKSPACE/dist/*.whl
    - name: Wheel dry-run 
      run: | 
        python -c "import skpackage; print(skpackage.__version__)"
    - name: Test the wheel 
      run: |
        python -m pytest tests/ --cov=skpackage --benchmark-skip
        coverage report -m